name: deploy-container

on:
  push:
    branches:
      - master
    paths:
      - 'packages/container/**'

defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GCP_BUCKET: ${{ secrets.GCP_BUCKET }}
      PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}

    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - run: yarn build
        env:
          PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}

      - name: Setup GCP
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true

      - name: Upload to GCP bucket
        run: gsutil -m rsync -d -c -r dist gs://$GCP_BUCKET/container/build

      - name: Invalidate Cache
        run: |
          gsutil -m setmeta -h "Cache-Control:public, max-age=1" gs://$GCP_BUCKET/container/build/index.html
          gsutil -m setmeta -h "Cache-Control:public, max-age=1" gs://$GCP_BUCKET/container/build/*.js
